import Footer from './components/Footer';
import './styles/globals.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700&display=swap"
          rel="preload"
          as='style'
        />
        <link rel="preload" href="/heroImg.webp" as="image"></link>
      </head>
      <body >
        <header style={{ textAlign: "left", paddingLeft: " 9rem " }}>
          <img src="/logo.webp" alt="Logo" className='headingLogo' />
        </header> 
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
